config/routes.rb
Portal::Application.routes.draw do
  resources :setups

  resources :banners  
  

end

app/models/setup.rb
class Setup < ActiveRecord::Base
  
  attr_accessible  :max_banner_image, :max_vehicle_image
  
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController
  # GET /setups
  # GET /setups.json
  def index
    @setups = Setup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @setups }
    end
  end

  # GET /setups/1
  # GET /setups/1.json
  def show
    @setup = Setup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setup }
    end
  end

  # GET /setups/new
  # GET /setups/new.json
  def new
    @setup = Setup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setup }
    end
  end

  # GET /setups/1/edit
  def edit
    @setup = Setup.find(params[:id])
  end

  # POST /setups
  # POST /setups.json
  def create
    @setup = Setup.new(params[:setup])

    respond_to do |format|
      if @setup.save
        format.html { redirect_to @setup, notice: 'Setup was successfully created.' }
        format.json { render json: @setup, status: :created, location: @setup }
      else
        format.html { render action: "new" }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /setups/1
  # PUT /setups/1.json
  def update
    @setup = Setup.find(params[:id])

    respond_to do |format|
      if @setup.update_attributes(params[:setup])
        format.html { redirect_to @setup, notice: 'Setup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setups/1
  # DELETE /setups/1.json
  def destroy
    @setup = Setup.find(params[:id])
    @setup.destroy

    respond_to do |format|
      format.html { redirect_to setups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/views/setups/_form.html.erb
<%= form_for(@setup) do |f| %>
  <% if @setup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setup.errors.count, "error") %> prohibited this setup from being saved:</h2>

      <ul>
      <% @setup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :max_banner_image %><br />
    <%= f.text_field :max_banner_image %>
  </div>
  <div class="field">
    <%= f.label :max_vehicle_image %><br />
    <%= f.text_field :max_vehicle_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setups/edit.html.erb
<h1>Editing setup</h1>

<%= render 'form' %>

<%= link_to 'Show', @setup %> |
<%= link_to 'Back', setups_path %>

app/views/setups/index.html.erb
<h1>Listing setups</h1>

<table>
  <tr>
    <th>Max banner image</th>
    <th>Max vehicle image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @setups.each do |setup| %>
  <tr>
    <td><%= setup.max_banner_image %></td>
    <td><%= setup.max_vehicle_image %></td>
    <td><%= link_to 'Show', setup %></td>
    <td><%= link_to 'Edit', edit_setup_path(setup) %></td>
    <td><%= link_to 'Destroy', setup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Setup', new_setup_path %>

app/views/setups/new.html.erb
<h1>New setup</h1>

<%= render 'form' %>

<%= link_to 'Back', setups_path %>

app/views/setups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Max banner image:</b>
  <%= @setup.max_banner_image %>
</p>

<p>
  <b>Max vehicle image:</b>
  <%= @setup.max_vehicle_image %>
</p>


<%= link_to 'Edit', edit_setup_path(@setup) %> |
<%= link_to 'Back', setups_path %>