config/routes.rb
Portal::Application.routes.draw do
  resources :setups

  resources :banners  
  

end

app/models/banner.rb
class Banner < ActiveRecord::Base

  has_many :sponsors, :dependent => :destroy
  
  attr_accessible :banner, :height, :left, :top, :category, :width, :sponsors_attributes

  accepts_nested_attributes_for :sponsors, :allow_destroy => true
  
  validates :banner, :presence => true, :uniqueness => true
  validates :sponsors, :presence => true
  validates :top, :left, :height, :width, :presence => true, :numericality => { :only_integer => true }, :if => :personalized_size?
  validate :has_beween_1_and_x_pictures
    
  BANNER_CATEGORIES = {
    "(B1) Superior - 720x100"       => "B1",
    "(B2) Lat. direito - 270x350"   => "B2",
    "(B3) Lat. direito - 270x150"   => "B3",
    "(B4) Lat. direito - 270x350"   => "B4",
    "(B5) Inferior - 200x80"        => "B5",
    "(B6) Inferior - 200x80"        => "B6",
    "(B7) Inferior - 200x80"        => "B7",
    "(B8) Inferior - 200x80"        => "B8",
    "(P1) Personalizado - ???x???"  => "P1"}
  
    def has_beween_1_and_x_pictures
      undestroyed_sponsors_count = 0

      self.sponsors.each { |s| undestroyed_sponsors_count += 1 unless s.marked_for_destruction? }

      errors.add(:sponsor, "size - #{undestroyed_sponsors_count}") if undestroyed_sponsors_count < 1
      errors.add(:sponsor, "size + #{undestroyed_sponsors_count}") if undestroyed_sponsors_count > 3
    end
  
    def personalized_size?
      self.category == "P1"
    end
    
    def is_swf?(content_type)
      content_type == "application/x-shockwave-flash"
    end

end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  
  before_filter :load_banner_setup, :only => [:new, :create, :edit, :update]
  
  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banners }
    end
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
    @banner = Banner.find(params[:id])
     
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/new
  # GET /banners/new.json
  def new
    @banner = Banner.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/1/edit
  def edit
    @banner = Banner.find(params[:id])
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(params[:banner])
    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render json: @banner, status: :created, location: @banner }
      else
        format.html { render action: "new" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banners/1
  # PUT /banners/1.json
  def update
    @banner = Banner.find(params[:id])

    respond_to do |format|
      if @banner.update_attributes(params[:banner])
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to banners_url }
      format.json { head :no_content }
    end
  end
  
private  
  def load_banner_setup
    @setup = Setup.last || Setup.new(:max_banner_image  => 1)
  end 
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= nested_form_for(@banner, :html => {:multipart => true}) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :banner %><br />
    <%= f.text_field :banner %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select :category, Banner::BANNER_CATEGORIES.map {|key, value| [ key, value] } %>
  </div>
  <div class="field">
  	<%= f.fields_for :sponsors do |builder| %>
      <%= render "sponsor_fields", :f => builder, :banner => @banner %>
    <% end %> 
    <%= link_to_add_fields "Add Sponsor", f, :sponsors %>
    <%= hidden_field_tag :max_banner_image, @setup.max_banner_image %>
  </div>
  <div class="banner_custom">
    <div class="field">
      <%= f.label :top %><br />
      <%= f.text_field :top %>
    </div>
    <div class="field">
      <%= f.label :left %><br />
      <%= f.text_field :left %>
    </div>
    <div class="field">
      <%= f.label :width %><br />
      <%= f.text_field :width %>
    </div>
    <div class="field">
      <%= f.label :height %><br />
      <%= f.text_field :height %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banners/_form_OLD.html.erb
<%= nested_form_for(@banner, :html => {:multipart => true}) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :banner %><br />
    <%= f.text_field :banner %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.select(:category, Banner::BANNER_CATEGORIES.collect {|c| [c, Banner::BANNER_CATEGORIES.index(c)+1]}, {:prompt => '-'} ) %>
  </div>
  <div class="field">
    <%= f.fields_for :sponsors do |builder| %>
      <%= render "sponsor_fields", :f => builder, :banner => @banner %>
    <% end %> 
    <%= link_to_add_fields "Add Sponsor", f, :sponsors %>
    <%= hidden_field_tag :max_banner_image, @setup.max_banner_image %>
  </div>
  <div class="field">
    <%= f.label :top %><br />
    <%= f.text_field :top %>
  </div>
  <div class="field">
    <%= f.label :left %><br />
    <%= f.text_field :left %>
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banners/_sponsor_fields.html.erb
<div class="field">
	<%= f.label :image, "Imagem" %><br />

	<% if f.object.new_record? %>
	  <%= f.file_field :image %>
	<% end %>

	<% unless f.object.new_record? %>
	    <% unless @banner.is_swf?(f.object.image.content_type) %>
  		  <%= image_tag f.object.image.url(:original) %>
      <% else %>
        <%= swf_tag f.object.image.url(:original),
        :width  => f.object.which_size(@banner.category)[:w],
        :height => f.object.which_size(@banner.category)[:h]
        %>
      <% end %>
  <% end %>
  <div id="remove_link">
    <%= f.hidden_field :_destroy %>
    <%= link_to "remove", '#', class: "remove_fields" %>
  </div>
</div>

app/views/banners/edit.html.erb
<h1>Editing banner</h1>

<%= render 'form' %>

<%= link_to 'Show', @banner %> |
<%= link_to 'Back', banners_path %>

app/views/banners/index.html.erb
<h1>Listing banners</h1>

<table>
  <tr>
    <th>Banner</th>
    <th>Category</th>
    <th>Top</th>
    <th>Left</th>
    <th>Width</th>
    <th>Height</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @banners.each do |banner| %>
  <tr>
    <td><%= banner.banner %></td>
    <td><%= banner.category %></td>
    <td><%= banner.top %></td>
    <td><%= banner.left %></td>
    <td><%= banner.width %></td>
    <td><%= banner.height %></td>
    <td><%= link_to 'Show', banner %></td>
    <td><%= link_to 'Edit', edit_banner_path(banner) %></td>
    <td><%= link_to 'Destroy', banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>New banner</h1>

<%= render 'form' %>

<%= link_to 'Back', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Banner:</b>
  <%= @banner.banner %>
</p>

<p>
  <b>Category:</b>
  <%= @banner.category %>
</p>

<% if @banner.personalized_size? %>
  <p>
    <b>Top:</b>
    <%= @banner.top %>
  </p>

  <p>
    <b>Left:</b>
    <%= @banner.left %>
  </p>

  <p>
    <b>Width:</b>
    <%= @banner.width %>
  </p>

  <p>
    <b>Height:</b>
    <%= @banner.height %>
  </p>
<% end %>
<p>
  <b>Image:</b><br />
  <% @banner.sponsors.each do |im| %>
  <td>
  <% unless @banner.is_swf?(im.image.content_type) %>
    <%= image_tag  im.image.url(:original)%>
  <% else %>
	  <%= swf_tag im.image.url(:original),:width => im.which_size(@banner.category)[:w],:height => im.which_size(@banner.category)[:h]%>
	<% end %>
	</td>
	<% end %>
</p>


<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>